version: 3.0.0.{build}-alpha1

init:
  -ps: |
    If ($Env:APPVEYOR_REPO_TAG_NAME -match "-")
      Set-AppveyorBuildVariable -Name "IsPreRelease" -Value True
    Else
      Set-AppveyorBuildVariable -Name "IsPreRelease" -Value False

build_script: build.cmd pack

test:
  assemblies:
    - __compile\Bogus.Tests.dll

artifacts:
  - path: __package\*.nupkg
    name: NuGet

deploy:
    - provider: NuGet
      api_key:
          secure: 1nPS2ttf+N4+FUhd+GZycrL7YzSWQpZjnGOMCb5+pGJXSdx0IFvVF8xhTGna7B9t
      artifact: NuGet
      on:
          branch: /v\d+\.\d+\.\d+/
          appveyor_repo_tag: true